default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREAD") {5} %>
  host: <%= ENV.fetch('DATABASE_HOST' {'localhost'}) %>
  port: <%= ENV.fetch('DATABASE_PORT' { 5432 }) %>
  username: <%= ENV.fetch('DATABASE_USERNAME' {'library_user'} )%>
  password: <%= ENV.fetch('DATABASE_PASSWORD' { 'password' } )%>

development:
  <<: *default
  database: library_api_development

test:
  <<: *default
  database: library_api_test

production:
  <<: *default
  database: library_api_production
  url: <% ENV['DATABASE_URL'] %>